## Pre-declare environmental variables
environment-template-common: &environment-template-common
  DEBIAN_FRONTEND: "noninteractive"
  DEBIAN_PRIORITY: "critical"
  DEBCONF_NOWARNINGS: "yes"
  DEBFULLNAME: "GobySoft CircleCI"
  DEBEMAIL: "toby@gobysoft.org"
  QUILT_PATCHES: debian/patches
  QUILT_REFRESH_ARGS: "-p ab --no-timestamps --no-index --strip-trailing-whitespace"
  SOURCE_WORKING_DIRECTORY: "/root/package-src"

environment-template-amd64: &environment-template-amd64
  TARGET_ARCH: "amd64"
  DEB_BUILD_OPTIONS: "parallel=4"
  # one job only must do the source build for each distro
  DO_SOURCE_BUILD: "true"

environment-template-arm64: &environment-template-arm64
  TARGET_ARCH: "arm64"
  DEB_BUILD_OPTIONS: "parallel=4 nocheck"
  
environment-template-armhf: &environment-template-armhf
  TARGET_ARCH: "armhf"
  DEB_BUILD_OPTIONS: "parallel=4 nocheck"

environment-template-bullseye: &environment-template-bullseye
  DISTRO_RELEASE_CODENAME: "bullseye"
  DISTRO_RELEASE_VERSION: "debian11"

environment-template-bookworm: &environment-template-bookworm
  DISTRO_RELEASE_CODENAME: "bookworm"
  DISTRO_RELEASE_VERSION: "debian12"

environment-template-focal: &environment-template-focal
  DISTRO_RELEASE_CODENAME: "focal"
  DISTRO_RELEASE_VERSION: "ubuntu20.04"

environment-template-jammy: &environment-template-jammy
  DISTRO_RELEASE_CODENAME: "jammy"
  DISTRO_RELEASE_VERSION: "ubuntu22.04"

environment-template-noble: &environment-template-noble
  DISTRO_RELEASE_CODENAME: "noble"
  DISTRO_RELEASE_VERSION: "ubuntu24.04"
  
## Pre-declare Docker containers

docker-base-bullseye: &docker-base-bullseye
  - image: gobysoft/debian-build-base:11.1

docker-base-bookworm: &docker-base-bookworm
  - image: gobysoft/debian-build-base:12.1

docker-base-focal: &docker-base-focal
  - image: gobysoft/ubuntu-build-base:20.04.1

docker-base-jammy: &docker-base-jammy
  - image: gobysoft/ubuntu-build-base:22.04.1

docker-base-noble: &docker-base-noble
  - image: gobysoft/ubuntu-build-base:24.04.1
    
## Pre-declare job templates
job-template-amd64: &job-template-amd64
  working_directory: /root/debian
  steps:
    - checkout
    - run: &run-add-packages
        name: Add packages.gobysoft.org sources.list
        command: |
          apt-get update && apt-get -y install dirmngr apt-transport-https && 
          echo "deb http://packages.gobysoft.org/ubuntu/release/ ${DISTRO_RELEASE_CODENAME}/" >> /etc/apt/sources.list.d/gobysoft_release.list && 
          apt-key adv --recv-key --keyserver keyserver.ubuntu.com 19478082E2F8D3FE || true
    - run: &run-update-apt
        name: Update apt packages
        command: apt-get update && apt-get dist-upgrade -y
    - run: &run-import-gpg
        name: Import GPG key
        command: echo -e "$GPG_KEY" | gpg --import
    - attach-workspace: &attach-src-workspace
        at: /root/src
    - run: &run-extract-src
        name: Extract the original source tarball
        command: |
          cp /root/src/*.orig.tar.gz ${CIRCLE_WORKING_DIRECTORY}/.. &&
          mkdir -p ${SOURCE_WORKING_DIRECTORY} && cd ${SOURCE_WORKING_DIRECTORY} &&
          tar xfz ../*.orig.tar.gz --strip-components=1
    - run: &run-nest-deb
        name: Nest debian source into project source and do changelog substitution
        command: |
          cp -r /root/debian ${SOURCE_WORKING_DIRECTORY} &&
          cp /root/src/changelog ${SOURCE_WORKING_DIRECTORY}/debian &&
          sed -i "s/DISTRORELEASEVERSION/${DISTRO_RELEASE_VERSION}/;s/DISTRORELEASECODENAME/${DISTRO_RELEASE_CODENAME}/" ${SOURCE_WORKING_DIRECTORY}/debian/changelog
    - run: &run-install-build-deps
        name: Install build dependencies
        command: |
          cd ${SOURCE_WORKING_DIRECTORY} &&
          mk-build-deps -a ${TARGET_ARCH} --host-arch ${TARGET_ARCH} --build-arch amd64 -t "apt-get -y --no-install-recommends -o Debug::pkgProblemResolver=yes" -i "debian/control" &&
          rm -f ${SOURCE_WORKING_DIRECTORY}/*-build-deps*.*
    - run: &run-build-pkg
        name: Build the Debian package 
        command: |
          cd ${SOURCE_WORKING_DIRECTORY} &&
          export DPKG_BUILDPACKAGE_BUILD_TYPE="-B"
          # default is to do source and binary build
          [[ "${DO_SOURCE_BUILD}" == "true" ]] && DPKG_BUILDPACKAGE_BUILD_TYPE=""        
          CONFIG_SITE=/etc/dpkg-cross/cross-config.${TARGET_ARCH} && dpkg-buildpackage -k19478082E2F8D3FE -a${TARGET_ARCH} ${DPKG_BUILDPACKAGE_BUILD_TYPE}
    - run: &run-store-next-build
        name: Store deb files for next build
        command: |
          cd ${SOURCE_WORKING_DIRECTORY} &&
          mkdir -p /root/deb &&
          find .. -maxdepth 1 -type f -exec cp {}  /root/deb \; &&
          rm -f /root/deb/*-build-deps*.deb
    - run: &run-store-for-artifacts
        name: Store deb files for storing artifacts
        command: mkdir -p /tmp/deb && cp /root/deb/* /tmp/deb
    - store_artifacts: &store
        path: /tmp/deb
    - run: &remove-orig-source
        name: Remove original source file to avoid conflicts in merging
        command: |        
          rm -f /root/deb/*.orig.tar.gz || true
    - persist_to_workspace: &persist-debs
        root: /root/deb
        paths:
          - '*.dsc'
          - '*.tar.xz'
          - '*.deb'
          - '*.ddeb'
          - '*.changes'
          - '*.buildinfo'
  
job-template-cross: &job-template-cross
  <<: *job-template-amd64

# base upload off noble build
job-template-upload: &job-template-upload
  <<: *job-template-amd64
  docker: *docker-base-noble
  
## Begin actual config
version: 2
workflows:
  version: 2
  commit:
    jobs:
      - get-orig-source
          
      # - amd64-buster-build:
      #     requires:
      #       - get-orig-source
      # - arm64-buster-build:
      #     requires:
      #       - get-orig-source
      # - armhf-buster-build:
      #     requires:
      #       - get-orig-source

      # - amd64-bullseye-build:
      #     requires:
      #       - get-orig-source
      # - arm64-bullseye-build:
      #     requires:
      #       - get-orig-source
      # - armhf-bullseye-build:
      #     requires:
      #       - get-orig-source

      - amd64-bookworm-build:
          requires:
            - get-orig-source
      - arm64-bookworm-build:
          requires:
            - get-orig-source
      - armhf-bookworm-build:
          requires:
            - get-orig-source

      # - amd64-focal-build:
      #     requires:
      #       - get-orig-source
      # - arm64-focal-build:
      #     requires:
      #       - get-orig-source
      # - armhf-focal-build:
      #     requires:
      #       - get-orig-source

      # - amd64-jammy-build:
      #     requires:
      #       - get-orig-source
      # - arm64-jammy-build:
      #     requires:
      #       - get-orig-source
      # - armhf-jammy-build:
      #     requires:
      #       - get-orig-source


      - amd64-noble-build:
          requires:
            - get-orig-source
      - arm64-noble-build:
          requires:
            - get-orig-source
      - armhf-noble-build:
          requires:
            - get-orig-source
            
            
      - continuous-upload:
          requires:
            # - arm64-bullseye-build
            # - arm64-focal-build
            # - arm64-jammy-build
            # - amd64-buster-build
            # - amd64-bullseye-build
            # - amd64-focal-build
            # - amd64-jammy-build
            # - armhf-bullseye-build
            # - armhf-focal-build
            # - armhf-jammy-build
            - amd64-bookworm-build
            - armhf-bookworm-build
            - arm64-bookworm-build
            - amd64-noble-build
            - armhf-noble-build
            - arm64-noble-build

      - release-upload:
          requires:
            - continuous-upload
jobs:
  get-orig-source:
    <<: *job-template-amd64
    docker: *docker-base-noble
    environment:
      <<: *environment-template-common
      <<: *environment-template-noble
      <<: *environment-template-amd64
    steps:
      - checkout
      - run:
          name: Install required packages
          command: |          
            apt-get update && apt-get -y install cdbs wget subversion locales
      - run:
          name: Configure locales
          command: |
            locale-gen en_US.utf8
      - run:
          name: Get original source tarball
          command: |
            cd .. &&
            make -f debian/rules get-orig-source &&
            mkdir -p /root/src &&
            mv *.tar.gz /root/src
      - run:
          name: Add changelog entry 
          command: |
            cd .. &&
            export NEWVERSION="$(echo /root/src/*.orig.tar.gz | sed 's/.*_\(.*\)\.orig\.tar\.gz/\1/')"
            COMMENT="Autobuild for version ${NEWVERSION}" &&
            dch --newversion=${NEWVERSION}-1~DISTRORELEASEVERSION.1 -D DISTRORELEASECODENAME "${COMMENT}" &&
            cp debian/changelog /root/src
      - store_artifacts:
          path: /root/src
      - persist_to_workspace:
          root: /root/src
          paths:
            - '*.tar.gz'
            - 'changelog'

  amd64-bullseye-build:
    <<: *job-template-amd64
    docker: *docker-base-bullseye
    environment:
      <<: *environment-template-common
      <<: *environment-template-bullseye
      <<: *environment-template-amd64
  arm64-bullseye-build: 
    <<: *job-template-cross
    docker: *docker-base-bullseye
    environment:
      <<: *environment-template-common
      <<: *environment-template-bullseye
      <<: *environment-template-arm64
  armhf-bullseye-build: 
    <<: *job-template-cross
    docker: *docker-base-bullseye
    environment:
      <<: *environment-template-common
      <<: *environment-template-bullseye
      <<: *environment-template-armhf

  amd64-bookworm-build:
    <<: *job-template-amd64
    docker: *docker-base-bookworm
    environment:
      <<: *environment-template-common
      <<: *environment-template-bookworm
      <<: *environment-template-amd64
  arm64-bookworm-build: 
    <<: *job-template-cross
    docker: *docker-base-bookworm
    environment:
      <<: *environment-template-common
      <<: *environment-template-bookworm
      <<: *environment-template-arm64
  armhf-bookworm-build: 
    <<: *job-template-cross
    docker: *docker-base-bookworm
    environment:
      <<: *environment-template-common
      <<: *environment-template-bookworm
      <<: *environment-template-armhf

  amd64-focal-build:
    <<: *job-template-amd64
    docker: *docker-base-focal
    environment:
      <<: *environment-template-common
      <<: *environment-template-focal
      <<: *environment-template-amd64
  arm64-focal-build: 
    <<: *job-template-cross
    docker: *docker-base-focal
    environment:
      <<: *environment-template-common
      <<: *environment-template-focal
      <<: *environment-template-arm64
  armhf-focal-build: 
    <<: *job-template-cross
    docker: *docker-base-focal
    environment:
      <<: *environment-template-common
      <<: *environment-template-focal
      <<: *environment-template-armhf

  amd64-jammy-build:
    <<: *job-template-amd64
    docker: *docker-base-jammy
    environment:
      <<: *environment-template-common
      <<: *environment-template-jammy
      <<: *environment-template-amd64
  arm64-jammy-build: 
    <<: *job-template-cross
    docker: *docker-base-jammy
    environment:
      <<: *environment-template-common
      <<: *environment-template-jammy
      <<: *environment-template-arm64
  armhf-jammy-build: 
    <<: *job-template-cross
    docker: *docker-base-jammy
    environment:
      <<: *environment-template-common
      <<: *environment-template-jammy
      <<: *environment-template-armhf


  amd64-noble-build:
    <<: *job-template-amd64
    docker: *docker-base-noble
    environment:
      <<: *environment-template-common
      <<: *environment-template-noble
      <<: *environment-template-amd64
  arm64-noble-build: 
    <<: *job-template-cross
    docker: *docker-base-noble
    environment:
      <<: *environment-template-common
      <<: *environment-template-noble
      <<: *environment-template-arm64
  armhf-noble-build: 
    <<: *job-template-cross
    docker: *docker-base-noble
    environment:
      <<: *environment-template-common
      <<: *environment-template-noble
      <<: *environment-template-armhf

      
      
  continuous-upload:
    <<: *job-template-upload
    environment:
      <<: *environment-template-common
      <<: *environment-template-noble
      <<: *environment-template-amd64
      UPLOAD_DESTINATION: "gobysoft-continuous"
    steps: &steps-upload
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "cd:15:c9:43:48:20:c9:56:58:9e:91:01:74:0d:fe:d2"
      - run: *run-import-gpg
      - attach-workspace:
          at: /root/deb
      - attach-workspace: *attach-src-workspace
      - run:
          name: Move original source into output directory
          command: mv /root/src/* /root/deb
      - run:
          name: Upload packages to packages.gobysoft.org
          command: |
            echo 'trusted-key A8E48CFF6650A07F6EF2B9AD19478082E2F8D3FE' >> ~/.gnupg/gpg.conf
            echo '|1|HjIjI40ko7XtgqXNK8DNuiVcy4Q=|7PEGcXNRmsj1tzGeRjb9UgWIWwE= ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIK8LmTLyo7inmKCa28F2JZBSpQFT1VrwnFpeV1v6PlQE' >> ~/.ssh/known_hosts
            for change_file in /root/deb/*.changes;
            do dput -c ${CIRCLE_WORKING_DIRECTORY}/.circleci/dput.cf ${UPLOAD_DESTINATION} $change_file;
            done
          

  release-upload:
    <<: *job-template-upload
    environment:
      <<: *environment-template-common
      <<: *environment-template-noble
      <<: *environment-template-amd64
      UPLOAD_DESTINATION: "gobysoft-release"
    steps: *steps-upload
